 global:
   scrape_interval:     10s # By default, scrape targets every 15 seconds.
   evaluation_interval: 10s

 # A scrape configuration containing exactly one endpoint to scrape:
 # Here it's Prometheus itself.
 scrape_configs:
   - job_name: "prometheus"
     static_configs:
       - targets: ["prometheus:9090"]

   - job_name: "tuiapp"
     
     # Override the global default and scrape targets from this job every 5 seconds.
     scrape_interval: 5s
     metrics_path: /metrics
     
     static_configs:
       - targets: ["tuiapp:8000"]